### ISSUE TITLE
Verify files are served with the correct MIME types

### ISSUE THREAD

**Issue by mathiasbynens** [remy/servedir#5]
Using servedir 0.1.5, I get this: http://i.imgur.com/BdMvh.png

It seems all non-HTML files seem are being sent as `text/plain`.

**Comment by remy** [comment]
Are you absolutely sure?  I'm running v0.1.5 and when I run:

```
curl -I http://localhost:8001/myimage.png
```

I see a header of `image/png`, when I request a file type that's unknown, I get:

```
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Connection: keep-alive
```

Where are you seeing `text/plain` (i.e. command line or web inspector, etc)

**Comment by mathiasbynens** [comment]
That was Chromium’s Web Inspector.

I really didn’t have the time to look into it so I quickly submitted this ticket and switched to Python’s SimpleHTTPServer.

I updated my node installation to the latest version on git and also installed a new Chromium nightly (I install a new one once a day or so) and now the problem seems to be gone. Might’ve been a weird Chromium bug that has been fixed…

**Comment by ghost** [comment]
I can't reproduce this, either. servedir's default MIME type is `application/octet-stream`, though, not `text/plain`, so it's most likely a Chromium bug.
