### ISSUE TITLE
v0.2.0: log requests

### ISSUE THREAD

**Issue by mathiasbynens** [remy/servedir#6]
Python’s SimpleHTTPServer logs every request back to the console, which is particularly useful to detect requests that result in 404 errors. It would be nice to have this kind of functionality in servedir, maybe with an option to filter the log so that it only shows errors.

**Comment by remy** [comment]
Yeah, I'm kinda hoping that @kitgoncharov will be compelled to add this for me ;-)

**Comment by mathiasbynens** [comment]
I can take a look later tonight if you want, I just quickly filed this because I don’t have the time right now.

**Comment by remy** [comment]
Worth filing for sure :)

**Comment by ghost** [comment]
Yes, this is something that I am currently working on for v0.2. I'll try to get a stable version finished and pushed to a new branch by the end of this week.

**Comment by remy** [comment]
@kitgoncharov - looking forward to seeing the branch :) (this is the win part of open source projects!)

**Comment by mathiasbynens** [comment]
That’s great news, Kit :)

Might be a good idea to file issues here for stuff that you’re working on, just so peeps like me won’t needlessly report them. Thoughts?

**Comment by ghost** [comment]
Agreed. I have to leave for school soon, but I'll open the necessary tickets as soon as I get home. =)

**Comment by remy** [comment]
Baked in to 0.1.10 - on by default, turn off using `-q`.
