### ISSUE TITLE
v0.2.0: Add support for using `servedir` as a module

### ISSUE THREAD

**Issue by ghost** [remy/servedir#8]
Python's `SimpleHTTPServer` can be used as both a module and a command-line utility. `servedir` v0.1.9 added partial support for this, but v0.2.0 could expose a subclass of `http.Server`, allowing developers to create simple servers from their unit testing files. This will also add support for custom events, which can be used to simplify the process of serving files and directories.

**Comment by alessioalex** [comment]
This is obsolete as you can use it as a module (I do): https://github.com/remy/servedir/blob/master/lib/servedir.js#L30

An example should be added to the readme.
